# Generated by Django 5.0.14 on 2025-11-25 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('organisation', models.CharField(blank=True, max_length=200, verbose_name='Organisation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('couleur', models.CharField(default='#1e40af', help_text="Couleur d'affichage dans le calendrier (format hex)", max_length=7, verbose_name='Couleur')),
                ('notification_envoyee', models.BooleanField(default=False, verbose_name='Notification envoyée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('participants', models.ManyToManyField(blank=True, related_name='reunions', to='meetings.participant', verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'Réunion',
                'verbose_name_plural': 'Réunions',
                'ordering': ['-date_debut'],
            },
        ),
    ]
