# Generated by Django 5.0 on 2026-01-06 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Administrateur"), ("USER", "Utilisateur")],
                        default="USER",
                        max_length=10,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "can_make_reservation",
                    models.BooleanField(
                        default=False, verbose_name="Peut créer des réservations"
                    ),
                ),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=True,
                        help_text="L'utilisateur doit changer son mot de passe à la première connexion",
                        verbose_name="Doit changer le mot de passe",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Utilisateur",
                "verbose_name_plural": "Profils Utilisateurs",
                "ordering": ["-created_at"],
            },
        ),
    ]
